version: "3"
services:
  ubuntu:
    image: ubuntu-rust-test-image
    user: pimeys
    volumes:
      - /home/pimeys/code:/code
    networks:
      - test-env

  chinook:
    image: postgres:13
    restart: always
    command: postgres -c 'max_connections=100'
    environment:
      POSTGRES_PASSWORD: "prisma"
    ports:
      - "5432:5432"
    networks:
      - test-env
    volumes:
      - ./chinook-entrypoint:/docker-entrypoint-initdb.d

networks:
  test-env:
